-- AlterTable
ALTER TABLE "User" ALTER COLUMN "tgl_lahir" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tgl_lahir" SET DATA TYPE DATE,
ALTER COLUMN "tgl_gabung" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tgl_gabung" SET DATA TYPE DATE;
